# -*- coding: utf-8 -*-
"""Analisis Performa Penjualan E-Commerce Global Menggunakan PySpark dan Visualisasi Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_PncOLvL1AiK_DrnUmNdBYk3xX1LqKQ

# Final Project Big Data Analytics  
## Analisis Performa Penjualan E-Commerce Global Menggunakan PySpark dan Visualisasi Data

Notebook ini dibuat untuk memenuhi tugas **Final Project Big Data Analytics** dengan kombinasi:
- Apache Spark / PySpark untuk pemrosesan data
- Spark SQL untuk analisis
- Visualisasi data
- Spark MLlib untuk prediksi return produk

Dataset: `synthetic_ecommerce_sales_2025.csv`

## 1. Latar Belakang

E-commerce menghasilkan banyak data transaksi yang dapat dimanfaatkan untuk memahami performa bisnis, perilaku pelanggan, efektivitas metode pembayaran, tren penjualan, serta risiko return produk.

Dataset yang digunakan merupakan dataset sintetis transaksi e-commerce global tahun 2023–2025. Data ini cocok digunakan untuk simulasi proses Big Data Analytics karena memiliki jumlah record yang cukup besar, berbagai fitur transaksi, fitur pelanggan, wilayah, metode pembayaran, rating, diskon, dan status pengembalian produk.

## 2. Rumusan Masalah / Business Questions

Analisis dalam proyek ini diarahkan untuk menjawab beberapa pertanyaan berikut:

1. Kategori produk apa yang menghasilkan revenue tertinggi?
2. Region mana yang memberikan kontribusi revenue terbesar?
3. Metode pembayaran apa yang paling sering digunakan pelanggan?
4. Bagaimana tren revenue bulanan dari tahun 2023 sampai 2025?
5. Kategori produk mana yang memiliki tingkat return tertinggi?
6. Apakah lama pengiriman berkaitan dengan rating pelanggan?
7. Apakah status return produk dapat diprediksi menggunakan machine learning?

## 3. Instalasi dan Import Library

Jalankan cell berikut. Jika PySpark belum tersedia, notebook akan mencoba menginstalnya secara otomatis.
"""

import sys
import subprocess
import importlib.util

if importlib.util.find_spec("pyspark") is None:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "pyspark"])

import os
import pandas as pd
import matplotlib.pyplot as plt

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, count, when, sum as spark_sum, avg, round as spark_round,
    year, month, date_format, to_date, desc
)

from pyspark.ml import Pipeline
from pyspark.ml.feature import StringIndexer, OneHotEncoder, VectorAssembler
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.evaluation import BinaryClassificationEvaluator, MulticlassClassificationEvaluator

print("Library berhasil di-load.")

"""## 4. Membuat Spark Session"""

spark = SparkSession.builder \
    .appName("Final Project Big Data E-Commerce Sales 2025") \
    .config("spark.sql.shuffle.partitions", "8") \
    .getOrCreate()

spark

"""## 5. Load Dataset

Pastikan file CSV berada dalam folder yang sama dengan notebook, atau ubah nilai `DATA_PATH` sesuai lokasi file.
"""

DATA_PATH = "synthetic_ecommerce_sales_2025.csv"

# Alternatif path jika dijalankan di lingkungan ChatGPT/Jupyter lokal:
if not os.path.exists(DATA_PATH) and os.path.exists("/mnt/data/synthetic_ecommerce_sales_2025.csv"):
    DATA_PATH = "/mnt/data/synthetic_ecommerce_sales_2025.csv"

df = spark.read.csv(DATA_PATH, header=True, inferSchema=True)

print("Jumlah baris:", df.count())
print("Jumlah kolom:", len(df.columns))
df.show(5, truncate=False)

"""## 6. Penjelasan Dataset

Dataset terdiri dari beberapa kolom utama:

| Kolom | Keterangan |
|---|---|
| `order_id` | ID transaksi |
| `customer_id` | ID pelanggan |
| `product_category` | Kategori produk |
| `product_price` | Harga produk |
| `quantity` | Jumlah produk |
| `order_date` | Tanggal pemesanan |
| `region` | Wilayah pelanggan |
| `payment_method` | Metode pembayaran |
| `delivery_days` | Lama pengiriman dalam hari |
| `is_returned` | Status return, 1 = return dan 0 = tidak return |
| `customer_rating` | Rating pelanggan |
| `discount_percent` | Persentase diskon |
| `revenue` | Pendapatan transaksi |

## 7. Exploratory Data Analysis

Tahap ini dilakukan untuk memahami struktur data, tipe data, jumlah record, missing value, duplikasi, dan statistik deskriptif.
"""

df.printSchema()

print("Jumlah baris:", df.count())
print("Jumlah kolom:", len(df.columns))
print("Daftar kolom:")
print(df.columns)

print("Statistik deskriptif kolom numerik:")
df.describe().show()

print("Jumlah missing value per kolom:")

missing_df = df.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in df.columns
])

missing_df.show()

total_rows = df.count()
unique_rows = df.dropDuplicates().count()
duplicate_rows = total_rows - unique_rows

print("Total baris:", total_rows)
print("Jumlah baris unik:", unique_rows)
print("Jumlah duplikasi:", duplicate_rows)

print("Distribusi kategori produk:")
df.groupBy("product_category").count().orderBy(desc("count")).show()

print("Distribusi region:")
df.groupBy("region").count().orderBy(desc("count")).show()

print("Distribusi metode pembayaran:")
df.groupBy("payment_method").count().orderBy(desc("count")).show()

"""## 8. Data Cleaning

Berdasarkan pengecekan awal, dataset tidak memiliki missing value dan tidak memiliki duplikasi. Namun, proses cleaning tetap dilakukan agar alur proyek sesuai dengan tahapan data analytics.

Proses yang dilakukan:
- Menghapus data duplikat.
- Menghapus baris yang memiliki nilai kosong.
- Mengubah kolom `order_date` menjadi tipe tanggal.
"""

df_clean = df.dropDuplicates()
df_clean = df_clean.dropna()
df_clean = df_clean.withColumn("order_date", to_date(col("order_date")))

print("Jumlah data setelah cleaning:", df_clean.count())
df_clean.printSchema()

"""## 9. Transformasi dan Enrichment Data

Pada tahap ini dilakukan penambahan fitur baru agar data lebih mudah dianalisis:

- `year`: tahun transaksi
- `month`: bulan transaksi
- `year_month`: gabungan tahun dan bulan
- `quarter`: kuartal transaksi
- `net_revenue`: revenue yang dihitung hanya untuk transaksi yang tidak direturn
"""

df_transformed = df_clean \
    .withColumn("year", year(col("order_date"))) \
    .withColumn("month", month(col("order_date"))) \
    .withColumn("year_month", date_format(col("order_date"), "yyyy-MM")) \
    .withColumn("quarter", date_format(col("order_date"), "yyyy-'Q'Q")) \
    .withColumn(
        "net_revenue",
        when(col("is_returned") == 0, col("revenue")).otherwise(0)
    )

df_transformed.show(5, truncate=False)

df_transformed.createOrReplaceTempView("ecommerce_sales")

spark.sql("""
    SELECT
        COUNT(*) AS total_transactions,
        ROUND(SUM(revenue), 2) AS total_revenue,
        ROUND(AVG(revenue), 2) AS avg_revenue,
        ROUND(AVG(customer_rating), 2) AS avg_rating,
        ROUND(AVG(delivery_days), 2) AS avg_delivery_days,
        ROUND(AVG(is_returned) * 100, 2) AS return_rate_percent
    FROM ecommerce_sales
""").show()

"""## 10. Analisis 1 — Total Revenue per Kategori Produk"""

revenue_category = df_transformed.groupBy("product_category") \
    .agg(spark_round(spark_sum("revenue"), 2).alias("total_revenue")) \
    .orderBy(desc("total_revenue"))

revenue_category.show()

revenue_category_pd = revenue_category.toPandas()

plt.figure(figsize=(10, 5))
plt.bar(revenue_category_pd["product_category"], revenue_category_pd["total_revenue"])
plt.title("Total Revenue per Kategori Produk")
plt.xlabel("Kategori Produk")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight:**  
Grafik ini menunjukkan kategori produk dengan kontribusi revenue terbesar. Kategori dengan revenue tertinggi dapat menjadi fokus utama strategi penjualan, promosi, dan pengelolaan stok.

## 11. Analisis 2 — Total Revenue per Region
"""

revenue_region = df_transformed.groupBy("region") \
    .agg(spark_round(spark_sum("revenue"), 2).alias("total_revenue")) \
    .orderBy(desc("total_revenue"))

revenue_region.show()

revenue_region_pd = revenue_region.toPandas()

plt.figure(figsize=(10, 5))
plt.bar(revenue_region_pd["region"], revenue_region_pd["total_revenue"])
plt.title("Total Revenue per Region")
plt.xlabel("Region")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight:**  
Region dengan revenue tertinggi menunjukkan wilayah yang memiliki kontribusi besar terhadap penjualan. Namun, jika selisih antar region tidak terlalu besar, kesimpulan yang lebih aman adalah performa penjualan relatif tersebar merata.

## 12. Analisis 3 — Distribusi Metode Pembayaran
"""

payment_distribution = df_transformed.groupBy("payment_method") \
    .agg(count("*").alias("total_transactions")) \
    .orderBy(desc("total_transactions"))

payment_distribution.show()

payment_distribution_pd = payment_distribution.toPandas()

plt.figure(figsize=(8, 5))
plt.bar(payment_distribution_pd["payment_method"], payment_distribution_pd["total_transactions"])
plt.title("Distribusi Metode Pembayaran")
plt.xlabel("Metode Pembayaran")
plt.ylabel("Jumlah Transaksi")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

"""**Insight:**  
Visualisasi ini digunakan untuk melihat metode pembayaran yang paling sering digunakan pelanggan. Jika distribusi antar metode pembayaran hampir seimbang, maka tidak ada satu metode yang benar-benar mendominasi.

## 13. Analisis 4 — Tren Revenue Bulanan
"""

monthly_revenue = df_transformed.groupBy("year_month") \
    .agg(spark_round(spark_sum("revenue"), 2).alias("total_revenue")) \
    .orderBy("year_month")

monthly_revenue.show(50)

monthly_revenue_pd = monthly_revenue.toPandas()

plt.figure(figsize=(12, 5))
plt.plot(monthly_revenue_pd["year_month"], monthly_revenue_pd["total_revenue"], marker="o")
plt.title("Tren Revenue Bulanan 2023–2025")
plt.xlabel("Bulan")
plt.ylabel("Total Revenue")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""**Insight:**  
Grafik line chart membantu melihat pola naik-turun revenue dari waktu ke waktu. Jika terdapat lonjakan pada bulan tertentu, hal tersebut dapat dikaitkan dengan pola musiman, promosi besar, atau periode belanja tertentu.

## 14. Analisis 5 — Return Rate per Kategori Produk
"""

return_rate_category = df_transformed.groupBy("product_category") \
    .agg(
        count("*").alias("total_transactions"),
        spark_sum("is_returned").alias("total_returned"),
        spark_round((spark_sum("is_returned") / count("*")) * 100, 2).alias("return_rate_percent")
    ) \
    .orderBy(desc("return_rate_percent"))

return_rate_category.show()

return_rate_category_pd = return_rate_category.toPandas()

plt.figure(figsize=(10, 5))
plt.bar(return_rate_category_pd["product_category"], return_rate_category_pd["return_rate_percent"])
plt.title("Return Rate per Kategori Produk")
plt.xlabel("Kategori Produk")
plt.ylabel("Return Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight:**  
Kategori dengan return rate tinggi perlu dianalisis lebih lanjut karena dapat menunjukkan masalah pada kualitas produk, ekspektasi pelanggan, kesesuaian ukuran, pengemasan, atau deskripsi produk.

## 15. Analisis 6 — Hubungan Delivery Days dan Customer Rating
"""

rating_delivery = df_transformed.groupBy("delivery_days") \
    .agg(
        spark_round(avg("customer_rating"), 2).alias("avg_rating"),
        count("*").alias("total_transactions")
    ) \
    .orderBy("delivery_days")

rating_delivery.show()

rating_delivery_pd = rating_delivery.toPandas()

plt.figure(figsize=(10, 5))
plt.plot(rating_delivery_pd["delivery_days"], rating_delivery_pd["avg_rating"], marker="o")
plt.title("Rata-Rata Rating Berdasarkan Lama Pengiriman")
plt.xlabel("Delivery Days")
plt.ylabel("Average Customer Rating")
plt.tight_layout()
plt.show()

"""**Insight:**  
Analisis ini digunakan untuk melihat apakah lama pengiriman berkaitan dengan kepuasan pelanggan. Jika rating menurun saat delivery days meningkat, perusahaan perlu memperbaiki proses logistik.

## 16. Analisis Tambahan Menggunakan Spark SQL

Spark SQL digunakan untuk menunjukkan bahwa analisis tidak hanya dilakukan dengan DataFrame API, tetapi juga dengan query SQL.
"""

spark.sql("""
    SELECT
        product_category,
        region,
        COUNT(*) AS total_transactions,
        ROUND(SUM(revenue), 2) AS total_revenue,
        ROUND(AVG(customer_rating), 2) AS avg_rating,
        ROUND(AVG(is_returned) * 100, 2) AS return_rate_percent
    FROM ecommerce_sales
    GROUP BY product_category, region
    ORDER BY total_revenue DESC
    LIMIT 10
""").show()

"""## 17. Machine Learning — Prediksi Return Produk

Pada tahap ini dilakukan analisis prediktif untuk memprediksi apakah suatu transaksi berpotensi mengalami return.

- Target / label: `is_returned`
- Jenis masalah: klasifikasi biner
- Model: Random Forest Classifier dari Spark MLlib
- Fitur kategorikal: `product_category`, `region`, `payment_method`
- Fitur numerik: `product_price`, `quantity`, `delivery_days`, `customer_rating`, `discount_percent`, `revenue`

Catatan penting: dataset memiliki class imbalance karena jumlah transaksi yang return biasanya jauh lebih sedikit dibanding transaksi yang tidak return. Oleh karena itu, evaluasi tidak cukup hanya menggunakan accuracy, tetapi juga F1-score, precision, recall, dan AUC.
"""

ml_df = df_transformed.select(
    "product_category",
    "region",
    "payment_method",
    "product_price",
    "quantity",
    "delivery_days",
    "customer_rating",
    "discount_percent",
    "revenue",
    "is_returned"
)

ml_df.groupBy("is_returned").count().show()

total_ml_rows = ml_df.count()
majority_count = ml_df.groupBy("is_returned").count().orderBy(desc("count")).first()["count"]
baseline_accuracy = majority_count / total_ml_rows

print("Baseline accuracy jika selalu menebak kelas mayoritas:", round(baseline_accuracy, 4))

categorical_cols = ["product_category", "region", "payment_method"]
numeric_cols = [
    "product_price",
    "quantity",
    "delivery_days",
    "customer_rating",
    "discount_percent",
    "revenue"
]

indexers = [
    StringIndexer(
        inputCol=c,
        outputCol=c + "_index",
        handleInvalid="keep"
    )
    for c in categorical_cols
]

encoders = [
    OneHotEncoder(
        inputCol=c + "_index",
        outputCol=c + "_encoded"
    )
    for c in categorical_cols
]

feature_cols = [c + "_encoded" for c in categorical_cols] + numeric_cols

assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features"
)

rf = RandomForestClassifier(
    labelCol="is_returned",
    featuresCol="features",
    numTrees=80,
    maxDepth=6,
    seed=42
)

pipeline = Pipeline(stages=indexers + encoders + [assembler, rf])

train_df, test_df = ml_df.randomSplit([0.8, 0.2], seed=42)

print("Jumlah data training:", train_df.count())
print("Jumlah data testing:", test_df.count())

model = pipeline.fit(train_df)
predictions = model.transform(test_df)

predictions.select(
    "is_returned",
    "prediction",
    "probability",
    "product_category",
    "region",
    "payment_method"
).show(10, truncate=False)

"""## 18. Evaluasi Model"""

binary_evaluator = BinaryClassificationEvaluator(
    labelCol="is_returned",
    rawPredictionCol="rawPrediction",
    metricName="areaUnderROC"
)

multi_accuracy = MulticlassClassificationEvaluator(
    labelCol="is_returned",
    predictionCol="prediction",
    metricName="accuracy"
)

multi_f1 = MulticlassClassificationEvaluator(
    labelCol="is_returned",
    predictionCol="prediction",
    metricName="f1"
)

multi_precision = MulticlassClassificationEvaluator(
    labelCol="is_returned",
    predictionCol="prediction",
    metricName="weightedPrecision"
)

multi_recall = MulticlassClassificationEvaluator(
    labelCol="is_returned",
    predictionCol="prediction",
    metricName="weightedRecall"
)

auc = binary_evaluator.evaluate(predictions)
accuracy = multi_accuracy.evaluate(predictions)
f1 = multi_f1.evaluate(predictions)
precision = multi_precision.evaluate(predictions)
recall = multi_recall.evaluate(predictions)

print("AUC:", round(auc, 4))
print("Accuracy:", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1-score:", round(f1, 4))

print("Confusion Matrix:")
predictions.groupBy("is_returned", "prediction").count().orderBy("is_returned", "prediction").show()

"""**Interpretasi Evaluasi Model:**  

- **Accuracy** menunjukkan persentase prediksi yang benar secara keseluruhan.
- **Precision** menunjukkan seberapa tepat model ketika memprediksi suatu kelas.
- **Recall** menunjukkan kemampuan model menemukan data pada kelas tertentu.
- **F1-score** menyeimbangkan precision dan recall.
- **AUC** menunjukkan kemampuan model membedakan transaksi return dan tidak return.

Karena data return jumlahnya lebih sedikit, hasil accuracy yang tinggi belum tentu berarti model sudah baik. Perlu diperhatikan juga confusion matrix, recall, dan F1-score.

## 19. Kesimpulan

Berdasarkan analisis yang dilakukan, dapat disimpulkan bahwa:

1. Dataset e-commerce ini dapat digunakan untuk menganalisis performa penjualan berdasarkan kategori produk, region, metode pembayaran, waktu, return, dan rating pelanggan.
2. Analisis revenue per kategori dan region membantu mengetahui area bisnis dengan kontribusi pendapatan terbesar.
3. Analisis metode pembayaran membantu memahami preferensi transaksi pelanggan.
4. Tren revenue bulanan dapat digunakan untuk membaca pola musiman penjualan.
5. Return rate per kategori membantu menemukan kategori produk yang berpotensi menimbulkan kerugian operasional.
6. Analisis delivery days dan customer rating dapat membantu mengevaluasi pengaruh logistik terhadap kepuasan pelanggan.
7. Model Random Forest dari Spark MLlib dapat digunakan untuk membangun sistem prediksi return produk, tetapi hasilnya perlu dievaluasi secara hati-hati karena adanya class imbalance.

Karena dataset ini bersifat sintetis, kesimpulan bisnis tidak boleh dianggap sebagai kondisi perusahaan nyata. Fokus utama proyek ini adalah penerapan proses Big Data Analytics menggunakan PySpark dari tahap eksplorasi, cleaning, transformasi, visualisasi, sampai machine learning.

## 20. Saran Pengembangan

Beberapa pengembangan yang dapat dilakukan:

- Menambahkan teknik handling class imbalance seperti undersampling, oversampling, atau class weighting.
- Membandingkan beberapa model seperti Logistic Regression, Decision Tree, dan Gradient-Boosted Trees.
- Membuat dashboard interaktif menggunakan Power BI, Tableau, Looker Studio, atau Streamlit.
- Melakukan forecasting revenue bulanan menggunakan data time series.
"""

spark.stop()
print("Spark session dihentikan.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = '/content/synthetic_ecommerce_sales_2025.csv'
df = pd.read_csv(file_path)

# Basic info and first few rows
print("Dataset Info:")
display(df.info())
display(df.head())

# Summary Statistics for numerical columns
print("Summary Statistics:")
display(df.describe())

"""### Analisis Awal: Distribusi Pengembalian Barang (Problem A)
Mari kita lihat seberapa besar persentase barang yang dikembalikan secara keseluruhan.
"""

return_rate = df['is_returned'].value_counts(normalize=True) * 100
print(f"Persentase Pengembalian:\n{return_rate}")

sns.countplot(data=df, x='is_returned')
plt.title('Distribusi Pengembalian Barang (0: Tidak, 1: Ya)')
plt.show()

"""### Analisis Mendalam: Faktor Pemicu Pengembalian (Problem A)
Kita akan melihat apakah kategori produk tertentu atau durasi pengiriman yang lama berkontribusi pada tingkat retur.
"""

plt.figure(figsize=(12, 5))

# 1. Retur berdasarkan Kategori Produk
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='product_category', y='is_returned', estimator=lambda x: sum(x)/len(x)*100)
plt.title('Tingkat Retur per Kategori (%)')
plt.xticks(rotation=45)

# 2. Hubungan Durasi Pengiriman dengan Retur
plt.subplot(1, 2, 2)
sns.boxplot(data=df, x='is_returned', y='delivery_days')
plt.title('Durasi Pengiriman vs Status Retur')

plt.tight_layout()
plt.show()

# 3. Hubungan Rating Pelanggan dengan Retur
plt.figure(figsize=(8, 5))
sns.violinplot(data=df, x='is_returned', y='customer_rating')
plt.title('Distribusi Rating Pelanggan pada Barang Retur vs Non-Retur')
plt.show()

# Korelasi sederhana
print("Korelasi antara variabel numerik dan is_returned:")
display(df.select_dtypes(include=['number']).corr()['is_returned'].sort_values(ascending=False))

"""### Analisis Efektivitas Diskon (Problem B)
Kita akan menganalisis hubungan antara persentase diskon dengan jumlah barang yang terjual dan total pendapatan yang dihasilkan.
"""

plt.figure(figsize=(14, 6))

# 1. Diskon vs Rata-rata Kuantitas terjual
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='discount_percent', y='quantity')
plt.title('Rata-rata Kuantitas per Tingkat Diskon')

# 2. Diskon vs Total Revenue
plt.subplot(1, 2, 2)
discount_revenue = df.groupby('discount_percent')['revenue'].sum().reset_index()
sns.lineplot(data=discount_revenue, x='discount_percent', y='revenue', marker='o')
plt.title('Total Pendapatan berdasarkan Tingkat Diskon')

plt.tight_layout()
plt.show()

# Analisis korelasi spesifik untuk diskon
discount_corr = df[['discount_percent', 'quantity', 'revenue']].corr()
print("Matriks Korelasi Diskon:")
display(discount_corr)

"""### Analisis Kinerja Regional (Problem C)
Analisis ini bertujuan memetakan preferensi kategori produk dan metode pembayaran di berbagai wilayah untuk strategi pemasaran yang lebih tepat sasaran.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Kategori Produk Populer per Wilayah
region_category = df.groupby(['region', 'product_category']).size().unstack()
region_category.plot(kind='bar', stacked=True, figsize=(12, 6), colormap='viridis')
plt.title('Distribusi Kategori Produk per Wilayah')
plt.ylabel('Jumlah Transaksi')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# 2. Metode Pembayaran Favorit per Wilayah
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='region', hue='payment_method')
plt.title('Preferensi Metode Pembayaran per Wilayah')
plt.legend(title='Metode Pembayaran')
plt.show()

# 3. Rata-rata Rating per Wilayah
print("Rata-rata Rating Pelanggan per Wilayah:")
display(df.groupby('region')['customer_rating'].mean().sort_values(ascending=False))

"""### Analisis Kinerja Regional (Problem C)
Analisis ini bertujuan memetakan preferensi kategori produk dan metode pembayaran di berbagai wilayah untuk strategi pemasaran yang lebih tepat sasaran.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Kategori Produk Populer per Wilayah
region_category = df.groupby(['region', 'product_category']).size().unstack()
region_category.plot(kind='bar', stacked=True, figsize=(12, 6), colormap='viridis')
plt.title('Distribusi Kategori Produk per Wilayah')
plt.ylabel('Jumlah Transaksi')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# 2. Metode Pembayaran Favorit per Wilayah
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='region', hue='payment_method')
plt.title('Preferensi Metode Pembayaran per Wilayah')
plt.legend(title='Metode Pembayaran')
plt.show()

# 3. Rata-rata Rating per Wilayah
print("Rata-rata Rating Pelanggan per Wilayah:")
display(df.groupby('region')['customer_rating'].mean().sort_values(ascending=False))

"""### Analisis Kinerja Regional (Problem C)
Analisis ini bertujuan memetakan preferensi kategori produk dan metode pembayaran di berbagai wilayah untuk strategi pemasaran yang lebih tepat sasaran.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Kategori Produk Populer per Wilayah
region_category = df.groupby(['region', 'product_category']).size().unstack()
region_category.plot(kind='bar', stacked=True, figsize=(12, 6), colormap='viridis')
plt.title('Distribusi Kategori Produk per Wilayah')
plt.ylabel('Jumlah Transaksi')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# 2. Metode Pembayaran Favorit per Wilayah
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='region', hue='payment_method')
plt.title('Preferensi Metode Pembayaran per Wilayah')
plt.legend(title='Metode Pembayaran')
plt.show()

# 3. Rata-rata Rating per Wilayah
print("Rata-rata Rating Pelanggan per Wilayah:")
display(df.groupby('region')['customer_rating'].mean().sort_values(ascending=False))

"""### Analisis Kinerja Regional (Problem C)
Analisis ini bertujuan memetakan preferensi kategori produk dan metode pembayaran di berbagai wilayah untuk strategi pemasaran yang lebih tepat sasaran.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Kategori Produk Populer per Wilayah
plt.figure(figsize=(15, 6))
region_category = df.groupby(['region', 'product_category']).size().unstack()
region_category.plot(kind='bar', stacked=True, figsize=(12, 6))
plt.title('Distribusi Kategori Produk per Wilayah')
plt.ylabel('Jumlah Transaksi')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# 2. Metode Pembayaran Favorit per Wilayah
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='region', hue='payment_method')
plt.title('Preferensi Metode Pembayaran per Wilayah')
plt.legend(title='Metode Pembayaran')
plt.show()

# 3. Rata-rata Rating per Wilayah
print("Rata-rata Rating Pelanggan per Wilayah:")
display(df.groupby('region')['customer_rating'].mean().sort_values(ascending=False))

"""### Analisis Kinerja Regional (Problem C)
Analisis ini bertujuan memetakan preferensi kategori produk dan metode pembayaran di berbagai wilayah untuk strategi pemasaran yang lebih tepat sasaran.
"""

plt.figure(figsize=(15, 6))

# 1. Kategori Produk Populer per Wilayah
region_category = df.groupby(['region', 'product_category']).size().unstack()
region_category.plot(kind='bar', stacked=True, figsize=(12, 6), colormap='viridis')
plt.title('Distribusi Kategori Produk per Wilayah')
plt.ylabel('Jumlah Transaksi')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# 2. Metode Pembayaran Favorit per Wilayah
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='region', hue='payment_method')
plt.title('Preferensi Metode Pembayaran per Wilayah')
plt.legend(title='Metode Pembayaran')
plt.show()

# 3. Rata-rata Rating per Wilayah
print("Rata-rata Rating Pelanggan per Wilayah:")
display(df.groupby('region')['customer_rating'].mean().sort_values(ascending=False))

"""### Analisis Efektivitas Diskon (Problem B)
Kita akan menganalisis hubungan antara persentase diskon dengan jumlah barang yang terjual dan total pendapatan yang dihasilkan.
"""

plt.figure(figsize=(14, 6))

# 1. Diskon vs Rata-rata Kuantitas terjual
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='discount_percent', y='quantity')
plt.title('Rata-rata Kuantitas per Tingkat Diskon')

# 2. Diskon vs Total Revenue
plt.subplot(1, 2, 2)
discount_revenue = df.groupby('discount_percent')['revenue'].sum().reset_index()
sns.lineplot(data=discount_revenue, x='discount_percent', y='revenue', marker='o')
plt.title('Total Pendapatan berdasarkan Tingkat Diskon')

plt.tight_layout()
plt.show()

# Analisis korelasi spesifik untuk diskon
discount_corr = df[['discount_percent', 'quantity', 'revenue']].corr()
print("Matriks Korelasi Diskon:")
display(discount_corr)

"""### Analisis Efektivitas Diskon (Problem B)
Kita akan menganalisis hubungan antara persentase diskon dengan jumlah barang yang terjual dan total pendapatan yang dihasilkan.
"""

plt.figure(figsize=(14, 6))

# 1. Diskon vs Rata-rata Kuantitas terjual
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='discount_percent', y='quantity')
plt.title('Rata-rata Kuantitas per Tingkat Diskon')

# 2. Diskon vs Total Revenue
plt.subplot(1, 2, 2)
discount_revenue = df.groupby('discount_percent')['revenue'].sum().reset_index()
sns.lineplot(data=discount_revenue, x='discount_percent', y='revenue', marker='o')
plt.title('Total Pendapatan berdasarkan Tingkat Diskon')

plt.tight_layout()
plt.show()

# Analisis korelasi spesifik untuk diskon
discount_corr = df[['discount_percent', 'quantity', 'revenue']].corr()
print("Matriks Korelasi Diskon:")
display(discount_corr)

"""### Analisis Efektivitas Diskon (Problem B)
Kita akan menganalisis hubungan antara persentase diskon dengan jumlah barang yang terjual dan total pendapatan yang dihasilkan.
"""

plt.figure(figsize=(14, 6))

# 1. Diskon vs Rata-rata Kuantitas terjual
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='discount_percent', y='quantity')
plt.title('Rata-rata Kuantitas per Tingkat Diskon')

# 2. Diskon vs Total Revenue
plt.subplot(1, 2, 2)
discount_revenue = df.groupby('discount_percent')['revenue'].sum().reset_index()
sns.lineplot(data=discount_revenue, x='discount_percent', y='revenue', marker='o')
plt.title('Total Pendapatan berdasarkan Tingkat Diskon')

plt.tight_layout()
plt.show()

# Analisis korelasi spesifik untuk diskon
discount_corr = df[['discount_percent', 'quantity', 'revenue']].corr()
print("Matriks Korelasi Diskon:")
display(discount_corr)

"""### Analisis Efektivitas Diskon (Problem B)
Kita akan menganalisis hubungan antara persentase diskon dengan jumlah barang yang terjual dan total pendapatan yang dihasilkan.
"""

plt.figure(figsize=(14, 6))

# 1. Diskon vs Rata-rata Kuantitas terjual
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='discount_percent', y='quantity')
plt.title('Rata-rata Kuantitas per Tingkat Diskon')

# 2. Diskon vs Total Revenue
plt.subplot(1, 2, 2)
discount_revenue = df.groupby('discount_percent')['revenue'].sum().reset_index()
sns.lineplot(data=discount_revenue, x='discount_percent', y='revenue', marker='o')
plt.title('Total Pendapatan berdasarkan Tingkat Diskon')

plt.tight_layout()
plt.show()

# Analisis korelasi spesifik untuk diskon
discount_corr = df[['discount_percent', 'quantity', 'revenue']].corr()
print("Matriks Korelasi Diskon:")
display(discount_corr)

"""### Analisis Efektivitas Diskon (Problem B)
Kita akan menganalisis hubungan antara persentase diskon dengan jumlah barang yang terjual dan total pendapatan yang dihasilkan.
"""

plt.figure(figsize=(14, 6))

# 1. Diskon vs Rata-rata Kuantitas terjual
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='discount_percent', y='quantity')
plt.title('Rata-rata Kuantitas per Tingkat Diskon')

# 2. Diskon vs Total Revenue
plt.subplot(1, 2, 2)
discount_revenue = df.groupby('discount_percent')['revenue'].sum().reset_index()
sns.lineplot(data=discount_revenue, x='discount_percent', y='revenue', marker='o')
plt.title('Total Pendapatan berdasarkan Tingkat Diskon')

plt.tight_layout()
plt.show()

# Analisis korelasi spesifik untuk diskon
discount_corr = df[['discount_percent', 'quantity', 'revenue']].corr()
print("Matriks Korelasi Diskon:")
display(discount_corr)

"""### Analisis Mendalam: Faktor Pemicu Pengembalian (Problem A)
Kita akan melihat apakah kategori produk tertentu atau durasi pengiriman yang lama berkontribusi pada tingkat retur.
"""

plt.figure(figsize=(12, 5))

# 1. Retur berdasarkan Kategori Produk
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='product_category', y='is_returned', estimator=lambda x: sum(x)/len(x)*100)
plt.title('Tingkat Retur per Kategori (%)')
plt.xticks(rotation=45)

# 2. Hubungan Durasi Pengiriman dengan Retur
plt.subplot(1, 2, 2)
sns.boxplot(data=df, x='is_returned', y='delivery_days')
plt.title('Durasi Pengiriman vs Status Retur')

plt.tight_layout()
plt.show()

# 3. Hubungan Rating Pelanggan dengan Retur
plt.figure(figsize=(8, 5))
sns.violinplot(data=df, x='is_returned', y='customer_rating')
plt.title('Distribusi Rating Pelanggan pada Barang Retur vs Non-Retur')
plt.show()

# Korelasi sederhana
print("Korelasi antara variabel numerik dan is_returned:")
display(df.select_dtypes(include=['number']).corr()['is_returned'].sort_values(ascending=False))

"""### Analisis Mendalam: Faktor Pemicu Pengembalian (Problem A)
Kita akan melihat apakah kategori produk tertentu atau durasi pengiriman yang lama berkontribusi pada tingkat retur.
"""

plt.figure(figsize=(12, 5))

# 1. Retur berdasarkan Kategori Produk
plt.subplot(1, 2, 1)
sns.barplot(data=df, x='product_category', y='is_returned', estimator=lambda x: sum(x)/len(x)*100)
plt.title('Tingkat Retur per Kategori (%)')
plt.xticks(rotation=45)

# 2. Hubungan Durasi Pengiriman dengan Retur
plt.subplot(1, 2, 2)
sns.boxplot(data=df, x='is_returned', y='delivery_days')
plt.title('Durasi Pengiriman vs Status Retur')

plt.tight_layout()
plt.show()

# 3. Hubungan Rating Pelanggan dengan Retur
plt.figure(figsize=(8, 5))
sns.violinplot(data=df, x='is_returned', y='customer_rating')
plt.title('Distribusi Rating Pelanggan pada Barang Retur vs Non-Retur')
plt.show()

# Korelasi sederhana
print("Korelasi antara variabel numerik dan is_returned:")
display(df.select_dtypes(include=['number']).corr()['is_returned'].sort_values(ascending=False))

"""Berikut adalah draf **Latar Belakang** dan **Penjelasan Permasalahan** (*Background and Problem Statement*) yang dirancang khusus berdasarkan karakteristik dataset *Synthetic E-Commerce Sales Dataset 2025*.

Format ini sudah disesuaikan dengan struktur standar yang biasa digunakan dalam laporan analisis data, *data science project*, atau skripsi.

---

## 1. Latar Belakang (Background)

Pesatnya pertumbuhan industri *e-commerce* dalam beberapa tahun terakhir telah mengubah perilaku belanja masyarakat secara global. Kompetisi yang ketat antar-platform menuntut perusahaan untuk tidak hanya fokus pada peningkatan volume penjualan, tetapi juga pada **efisiensi operasional** dan **retensi pelanggan**. Di tengah dinamika ini, pemanfaatan data transaksi (*data-driven decision making*) menjadi kunci utama untuk mempertahankan keunggulan kompetitif.

Namun, dalam dunia nyata, data transaksi *e-commerce* sering kali bersifat sensitif karena mengandung informasi pribadi pelanggan (PII) dan rahasia bisnis yang dilindungi regulasi ketat (seperti GDPR). Sebagai solusinya, penggunaan dataset sintetis berkualitas tinggi—seperti *Synthetic E-Commerce Sales Dataset 2025*—menjadi jembatan penting.

Dataset ini merefleksikan pola transaksi dunia nyata dari Januari 2023 hingga Desember 2025. Di dalamnya, terdapat dinamika yang kompleks seperti variasi harga produk, preferensi metode pembayaran di wilayah tertentu, fluktuasi kepuasan pelanggan (*customer rating*), efisiensi logistik (*delivery days*), hingga kebijakan diskon.

Analisis mendalam terhadap data ini sangat krusial bagi perusahaan untuk memahami faktor apa saja yang mendorong profitabilitas, bagaimana meminimalkan kerugian akibat pengembalian barang, serta bagaimana meningkatkan kepuasan konsumen secara menyeluruh.

---

## 2. Penjelasan Permasalahan (Problem Statement)

Meskipun aktivitas penjualan berjalan secara masif, manajemen *e-commerce* sering kali menghadapi beberapa tantangan kritis yang belum terpecahkan secara optimal. Berdasarkan atribut yang tersedia dalam dataset, terdapat tiga masalah utama yang diidentifikasi:

### A. Tingginya Tingkat Pengembalian Barang (*Product Returns*)

Pengembalian barang (`is_returned`) merupakan salah satu beban biaya terbesar dalam logistik *e-commerce* (*reverse logistics*). Masalahnya adalah manajemen belum mengetahui secara pasti **kombinasi faktor apa saja yang paling memicu pelanggan melakukan retur**.

* Apakah retur disebabkan oleh kategori produk tertentu (misalnya *Fashion* karena masalah ukuran)?
* Apakah karena pengiriman yang terlalu lama (`delivery_days`) atau karena kualitas produk yang buruk (terindikasi dari `customer_rating` yang rendah)?

### B. Kebijakan Diskon yang Belum Optimal terhadap Pendapatan (*Revenue*)

Perusahaan sering kali memberikan potongan harga (`discount_percent`) untuk memicu volume penjualan (`quantity`). Namun, belum ada evaluasi apakah pemberian diskon ini benar-benar efektif meningkatkan total pendapatan (`revenue`), atau justru menggerus margin keuntungan. Perusahaan membutuhkan pola yang jelas mengenai **titik optimal persentase diskon** yang dapat meningkatkan volume penjualan tanpa merugikan bisnis.

### C. Ketimpangan Kinerja Penjualan Antar-Wilayah dan Kategori

Manajemen menghadapi tantangan dalam memetakan performa bisnis secara spesifik. Tanpa analisis prediktif, alokasi stok produk dan strategi pemasaran di berbagai wilayah (`region`) sering kali tidak tepat sasaran. Perusahaan perlu mengidentifikasi **kategori produk dan metode pembayaran apa yang mendominasi di wilayah tertentu**, serta bagaimana performa kepuasan pelanggan di wilayah tersebut untuk mencegah penurunan penjualan di masa mendatang.

---

> **Tips Tambahan:** Jika Anda menggunakan ini untuk proyek *Machine Learning*, Anda bisa menambahkan satu poin di akhir bahwa tujuan dari proyek ini adalah membangun model prediksi (misalnya: klasifikasi untuk memprediksi *product return* atau regresi untuk peramalan *revenue*).

Apakah Anda ingin saya bantu membuatkan tujuan penelitian (*research objectives*) atau metrik evaluasi yang cocok untuk dataset ini?

Untuk membuka fungsionalitas penuh semua Aplikasi, aktifkan [Aktivitas Aplikasi Gemini](https://myactivity.google.com/product/gemini).
"""